name: FenceLane Test Runner

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  ENCRYPTION_SECRET: "secret123"

jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use latest Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Yarn cache
        uses: c-hive/gha-yarn-cache@v2.1.0

      - name: Install JS dependencies
        run: yarn --immutable

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
